version: '3.9'
services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8084:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgresjuly'
    volumes:
      - ./src/main/resources/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    restart: always